import 'package:battle_master/components/mon.dart';

import '../../constants/type.dart';

final List<Pokemon> dex = [
  Pokemon(
      name: 'Bulbasaur',
      type1: Types.grass,
      type2: Types.poison,
      hp: 45,
      attack: 65,
      defense: 65,
      speed: 45),
  Pokemon(
      name: 'Ivysaur',
      type1: Types.grass,
      type2: Types.poison,
      hp: 60,
      attack: 80,
      defense: 80,
      speed: 60),
  Pokemon(
      name: 'Venusaur',
      type1: Types.grass,
      type2: Types.poison,
      hp: 80,
      attack: 100,
      defense: 100,
      speed: 80),
  Pokemon(
      name: 'Charmander',
      type1: Types.fire,
      hp: 39,
      attack: 60,
      defense: 50,
      speed: 65),
  Pokemon(
      name: 'Charmeleon',
      type1: Types.fire,
      hp: 58,
      attack: 80,
      defense: 65,
      speed: 80),
  Pokemon(
      name: 'Charizard',
      type1: Types.fire,
      type2: Types.flying,
      hp: 78,
      attack: 109,
      defense: 85,
      speed: 100),
  Pokemon(
      name: 'Squirtle',
      type1: Types.water,
      hp: 44,
      attack: 50,
      defense: 65,
      speed: 43),
  Pokemon(
      name: 'Wartortle',
      type1: Types.water,
      hp: 59,
      attack: 65,
      defense: 80,
      speed: 58),
  Pokemon(
      name: 'Blastoise',
      type1: Types.water,
      hp: 79,
      attack: 85,
      defense: 105,
      speed: 78),
  Pokemon(
      name: 'Caterpie',
      type1: Types.bug,
      hp: 45,
      attack: 30,
      defense: 35,
      speed: 45),
  Pokemon(
      name: 'Metapod',
      type1: Types.bug,
      hp: 50,
      attack: 25,
      defense: 55,
      speed: 30),
  Pokemon(
      name: 'Butterfree',
      type1: Types.bug,
      type2: Types.flying,
      hp: 60,
      attack: 90,
      defense: 80,
      speed: 70),
  Pokemon(
      name: 'Weedle',
      type1: Types.bug,
      type2: Types.poison,
      hp: 40,
      attack: 35,
      defense: 30,
      speed: 50),
  Pokemon(
      name: 'Kakuna',
      type1: Types.bug,
      type2: Types.flying,
      hp: 45,
      attack: 25,
      defense: 50,
      speed: 35),
  Pokemon(
      name: 'Beedrill',
      type1: Types.bug,
      type2: Types.poison,
      hp: 65,
      attack: 90,
      defense: 80,
      speed: 75),
  Pokemon(
      name: 'Pidgey',
      type1: Types.normal,
      type2: Types.flying,
      hp: 40,
      attack: 35,
      defense: 40,
      speed: 56),
  Pokemon(
      name: 'Pidgeotto',
      type1: Types.normal,
      type2: Types.flying,
      hp: 63,
      attack: 60,
      defense: 55,
      speed: 71),
  Pokemon(
      name: 'Pidgeot',
      type1: Types.normal,
      type2: Types.flying,
      hp: 83,
      attack: 80,
      defense: 75,
      speed: 101),
  Pokemon(
      name: 'Rattata',
      type1: Types.normal,
      hp: 30,
      attack: 56,
      defense: 35,
      speed: 72),
  Pokemon(
      name: 'Raticate',
      type1: Types.normal,
      hp: 55,
      attack: 81,
      defense: 70,
      speed: 97),
  Pokemon(
      name: 'Spearow',
      type1: Types.normal,
      type2: Types.flying,
      hp: 40,
      attack: 35,
      defense: 40,
      speed: 56),
  Pokemon(
      name: 'Fearow',
      type1: Types.normal,
      type2: Types.flying,
      hp: 65,
      attack: 90,
      defense: 65,
      speed: 100),
  Pokemon(
      name: 'Ekans',
      type1: Types.poison,
      hp: 35,
      attack: 60,
      defense: 54,
      speed: 55),
  Pokemon(
      name: 'Arbok',
      type1: Types.poison,
      hp: 65,
      attack: 95,
      defense: 79,
      speed: 80),
];
